#import "shaders.h"
#include "console_common/platform/platform.h"
#import <Foundation/Foundation.h>

/* Source is compiled once at startup. The C renderer supplies ordered quads;
 * Metal only handles their rasterization and presentation. */
NSString *cc_metal_shader_source(void) {
    return [NSString
        stringWithFormat:
            @"#define CC_WIDTH %d.0\n#define CC_HEIGHT %d.0\n%@%@%@%@", CC_FRAME_WIDTH,
            CC_FRAME_HEIGHT,
            @"#include <metal_stdlib>\n"
             "using namespace metal;\n"
             "\n"
             "struct CcVertex {\n"
             "    float2 position;\n"
             "    float2 uv[4];\n"
             "    float2 depth_w;\n"
             "    float4 color;\n"
             "};\n"
             "\n"
             "struct CcVertexOutput {\n"
             "    float4 position [[position]];\n"
             "    float2 uv0;\n"
             "    float2 uv1;\n"
             "    float2 uv2;\n"
             "    float2 uv3;\n"
             "    float4 color;\n"
             "};\n"
             "\n"
             "struct CcMaterialParams {\n"
             "    float4 r0;\n"
             "    float4 r1;\n"
             "    float4 kc3;\n"
             "    uint texture_count;\n"
             "    uint alpha_comparisons;\n"
             "    uint alpha_operation;\n"
             "    uint alpha_references;\n"
             "};\n"
             "\n"
             "vertex CcVertexOutput cc_vertex(const device CcVertex *vertices\n"
             "                                [[buffer(0)]],\n"
             "                                uint index [[vertex_id]]) {\n"
             "    CcVertexOutput output;\n"
             "    CcVertex input = vertices[index];\n"
             "    float w = input.depth_w.y;\n"
             "    float2 clip = float2(input.position.x * (2.0 / CC_WIDTH) - 1.0,\n"
             "                         1.0 - input.position.y * (2.0 / CC_HEIGHT));\n"
             "    output.position = float4(clip * w, input.depth_w.x * w, w);\n"
             "    output.uv0 = input.uv[0];\n"
             "    output.uv1 = input.uv[1];\n"
             "    output.uv2 = input.uv[2];\n"
             "    output.uv3 = input.uv[3];\n"
             "    output.color = input.color;\n"
             "    return output;\n"
             "}\n"
             "\n"
             "fragment float4 cc_fragment(CcVertexOutput input [[stage_in]],\n"
             "                            texture2d<float> image [[texture(0)]],\n"
             "                            sampler image_sampler [[sampler(0)]]) {\n"
             "    return image.sample(image_sampler, input.uv0) * input.color;\n"
             "}\n"
             "\n"
             "bool cc_compare_alpha(uint kind, float alpha, float reference) {\n"
             "    switch (kind) {\n"
             "        case 0u:\n"
             "            return false;\n"
             "        case 1u:\n"
             "            return alpha < reference;\n"
             "        case 2u:\n"
             "            return alpha == reference;\n"
             "        case 3u:\n"
             "            return alpha <= reference;\n"
             "        case 4u:\n"
             "            return alpha > reference;\n"
             "        case 5u:\n"
             "            return alpha != reference;\n"
             "        case 6u:\n"
             "            return alpha >= reference;\n"
             "        default:\n"
             "            return true;\n"
             "    }\n"
             "}\n"
             "\n"
             "bool cc_alpha_passes(uint comparisons, uint operation,\n"
             "                     uint references, float alpha) {\n"
             "    bool first = cc_compare_alpha(comparisons & 15u, alpha,\n"
             "                                  float(references & 255u));\n"
             "    bool second = cc_compare_alpha((comparisons >> 4) & 15u, alpha,\n"
             "                                   float((references >> 8) & 255u));\n"
             "    return operation == 0u ? (first && second) :\n"
             "           operation == 1u ? (first || second) :\n"
             "           operation == 2u ? (first != second) : (first == second);\n"
             "}\n"
             "\n"
             "fragment float4 cc_material_fragment(\n"
             "    CcVertexOutput input [[stage_in]],\n"
             "    constant CcMaterialParams &params [[buffer(0)]],\n"
             "    texture2d<float> image0 [[texture(0)]],\n"
             "    texture2d<float> image1 [[texture(1)]],\n"
             "    sampler sampler0 [[sampler(0)]],\n"
             "    sampler sampler1 [[sampler(1)]]) {\n"
             "    float4 p;\n"
             "    if (params.texture_count == 0u) {\n"
             "        p = params.r1 * input.color;\n"
             "    } else {\n"
             "        float4 t0 = image0.sample(sampler0, input.uv0);\n"
             "        if (params.texture_count == 1u) {\n"
             "            p = mix(params.r0, params.r1, t0) * input.color;\n"
             "        } else {\n"
             "            float4 t1 = image1.sample(sampler1, input.uv1);\n"
             "            p = mix(params.r0, params.r1,\n"
             "                    mix(t1, t0, params.kc3.a)) * input.color;\n"
             "        }\n"
             "    }\n"
             "    uint comparisons = params.alpha_comparisons;\n"
             "    uint operation = params.alpha_operation;\n"
             "    if (comparisons != 0x77u || operation >= 2u) {\n"
             "        float alpha = floor(p.a * 255.0 + 0.5);\n"
             "        alpha -= 256.0 * floor(alpha / 256.0);\n"
             "        if (!cc_alpha_passes(comparisons, operation,\n"
             "                             params.alpha_references, alpha)) {\n"
             "            discard_fragment();\n"
             "        }\n"
             "    }\n"
             "    return p;\n"
             "}\n"
             "\n",
            @"struct CcTevParams {\n"
             "    float4 regs[3];\n"
             "    float4 kc[4];\n"
             "    uint4 stage_words[6];\n"
             "    uint4 swap;\n"
             "    uint stage_count;\n"
             "    uint alpha_comparisons;\n"
             "    uint alpha_operation;\n"
             "    uint alpha_references;\n"
             "};\n"
             "\n"
             "uint cc_tev_byte(uint4 words, uint index) {\n"
             "    return (words[index >> 2] >> ((index & 3u) * 8u)) & 255u;\n"
             "}\n"
             "\n"
             "float4 cc_tev_swizzle(float4 color, uint pattern) {\n"
             "    return float4(color[pattern & 3u],\n"
             "                  color[(pattern >> 2) & 3u],\n"
             "                  color[(pattern >> 4) & 3u],\n"
             "                  color[(pattern >> 6) & 3u]);\n"
             "}\n"
             "\n"
             "float3 cc_tev_kcolor(uint selector, constant CcTevParams &params) {\n"
             "    if (selector < 8u) {\n"
             "        return float3(float(8u - selector) / 8.0);\n"
             "    }\n"
             "    if (selector >= 12u && selector < 16u) {\n"
             "        return params.kc[selector - 12u].rgb;\n"
             "    }\n"
             "    if (selector >= 16u) {\n"
             "        uint index = selector - 16u;\n"
             "        return float3(params.kc[index & 3u][index >> 2]);\n"
             "    }\n"
             "    return float3(1.0);\n"
             "}\n"
             "\n"
             "float cc_tev_kalpha(uint selector, constant CcTevParams &params) {\n"
             "    if (selector < 8u) {\n"
             "        return float(8u - selector) / 8.0;\n"
             "    }\n"
             "    if (selector >= 16u) {\n"
             "        uint index = selector - 16u;\n"
             "        return params.kc[index & 3u][index >> 2];\n"
             "    }\n"
             "    return 1.0;\n"
             "}\n"
             "\n"
             "float3 cc_tev_color_input(uint index, thread const float4 *regs,\n"
             "                          float4 tex, float4 ras, float3 kcolor) {\n"
             "    if (index < 8u) {\n"
             "        float4 reg = regs[index >> 1];\n"
             "        return (index & 1u) != 0u ? float3(reg.a) : reg.rgb;\n"
             "    }\n"
             "    switch (index) {\n"
             "        case 8u:\n"
             "            return tex.rgb;\n"
             "        case 9u:\n"
             "            return float3(tex.a);\n"
             "        case 10u:\n"
             "            return ras.rgb;\n"
             "        case 11u:\n"
             "            return float3(ras.a);\n"
             "        case 12u:\n"
             "            return float3(1.0);\n"
             "        case 13u:\n"
             "            return float3(0.5);\n"
             "        case 14u:\n"
             "            return kcolor;\n"
             "        default:\n"
             "            return float3(0.0);\n"
             "    }\n"
             "}\n"
             "\n"
             "float cc_tev_alpha_input(uint index, thread const float4 *regs,\n"
             "                         float4 tex, float4 ras, float kalpha) {\n"
             "    if (index < 4u) {\n"
             "        return regs[index].a;\n"
             "    }\n"
             "    switch (index) {\n"
             "        case 4u:\n"
             "            return tex.a;\n"
             "        case 5u:\n"
             "            return ras.a;\n"
             "        case 6u:\n"
             "            return kalpha;\n"
             "        default:\n"
             "            return 0.0;\n"
             "    }\n"
             "}\n"
             "\n"
             "float3 cc_tev_color8(float3 value) {\n"
             "    float3 rounded = floor(value * 255.0 + 0.5);\n"
             "    return rounded - 256.0 * floor(rounded / 256.0);\n"
             "}\n"
             "\n"
             "float cc_tev_alpha8(float value) {\n"
             "    float rounded = floor(value * 255.0 + 0.5);\n"
             "    return rounded - 256.0 * floor(rounded / 256.0);\n"
             "}\n"
             "\n",
            @"float3 cc_tev_color_op(uint ab, uint cd, uint op, uint control,\n"
             "                       thread const float4 *regs, float4 tex,\n"
             "                       float4 ras, float3 kcolor) {\n"
             "    float3 a = cc_tev_color_input(ab & 15u, regs, tex, ras, kcolor);\n"
             "    float3 b = cc_tev_color_input(ab >> 4, regs, tex, ras, kcolor);\n"
             "    float3 c = cc_tev_color_input(cd & 15u, regs, tex, ras, kcolor);\n"
             "    float3 d = cc_tev_color_input(cd >> 4, regs, tex, ras, kcolor);\n"
             "    uint kind = op & 15u;\n"
             "    float3 result;\n"
             "    if (kind >= 14u) {\n"
             "        float3 qa = cc_tev_color8(a);\n"
             "        float3 qb = cc_tev_color8(b);\n"
             "        bool3 passes = (kind & 1u) != 0u ? (qa == qb) : (qa > qb);\n"
             "        result = d + select(float3(0.0), c, passes);\n"
             "    } else if (kind >= 8u) {\n"
             "        float3 qa = cc_tev_color8(a);\n"
             "        float3 qb = cc_tev_color8(b);\n"
             "        float packed_a = qa.r;\n"
             "        float packed_b = qb.r;\n"
             "        if (kind >= 10u) {\n"
             "            packed_a += qa.g * 256.0;\n"
             "            packed_b += qb.g * 256.0;\n"
             "        }\n"
             "        if (kind >= 12u) {\n"
             "            packed_a += qa.b * 65536.0;\n"
             "            packed_b += qb.b * 65536.0;\n"
             "        }\n"
             "        bool pass = (kind & 1u) != 0u\n"
             "            ? packed_a == packed_b : packed_a > packed_b;\n"
             "        result = d + (pass ? c : float3(0.0));\n"
             "    } else {\n"
             "        uint bias_index = (op >> 4) & 3u;\n"
             "        float bias = bias_index == 1u ? 0.5 :\n"
             "                     bias_index == 2u ? -0.5 : 0.0;\n"
             "        uint scale_index = op >> 6;\n"
             "        float scale = scale_index == 1u ? 2.0 :\n"
             "                      scale_index == 2u ? 4.0 :\n"
             "                      scale_index == 3u ? 0.5 : 1.0;\n"
             "        float3 mixed = mix(a, b, c);\n"
             "        result = (d + (kind == 1u ? -mixed : mixed) + bias) * scale;\n"
             "    }\n"
             "    return (control & 1u) != 0u ? clamp(result, 0.0, 1.0) : result;\n"
             "}\n"
             "\n"
             "float cc_tev_alpha_op(uint ab, uint cd, uint op, uint control,\n"
             "                      thread const float4 *regs, float4 tex,\n"
             "                      float4 ras, float kalpha) {\n"
             "    float a = cc_tev_alpha_input(ab & 15u, regs, tex, ras, kalpha);\n"
             "    float b = cc_tev_alpha_input(ab >> 4, regs, tex, ras, kalpha);\n"
             "    float c = cc_tev_alpha_input(cd & 15u, regs, tex, ras, kalpha);\n"
             "    float d = cc_tev_alpha_input(cd >> 4, regs, tex, ras, kalpha);\n"
             "    uint kind = op & 15u;\n"
             "    float result;\n"
             "    if (kind >= 8u) {\n"
             "        float qa = cc_tev_alpha8(a);\n"
             "        float qb = cc_tev_alpha8(b);\n"
             "        bool pass = (kind & 1u) != 0u ? qa == qb : qa > qb;\n"
             "        result = d + (pass ? c : 0.0);\n"
             "    } else {\n"
             "        uint bias_index = (op >> 4) & 3u;\n"
             "        float bias = bias_index == 1u ? 0.5 :\n"
             "                     bias_index == 2u ? -0.5 : 0.0;\n"
             "        uint scale_index = op >> 6;\n"
             "        float scale = scale_index == 1u ? 2.0 :\n"
             "                      scale_index == 2u ? 4.0 :\n"
             "                      scale_index == 3u ? 0.5 : 1.0;\n"
             "        float mixed = mix(a, b, c);\n"
             "        result = (d + (kind == 1u ? -mixed : mixed) + bias) * scale;\n"
             "    }\n"
             "    return (control & 1u) != 0u ? clamp(result, 0.0, 1.0) : result;\n"
             "}\n"
             "\n",
            @"fragment float4 cc_tev_fragment(\n"
             "    CcVertexOutput input [[stage_in]],\n"
             "    constant CcTevParams &params [[buffer(0)]],\n"
             "    texture2d<float> image0 [[texture(0)]],\n"
             "    texture2d<float> image1 [[texture(1)]],\n"
             "    texture2d<float> image2 [[texture(2)]],\n"
             "    texture2d<float> image3 [[texture(3)]],\n"
             "    sampler sampler0 [[sampler(0)]],\n"
             "    sampler sampler1 [[sampler(1)]],\n"
             "    sampler sampler2 [[sampler(2)]],\n"
             "    sampler sampler3 [[sampler(3)]]) {\n"
             "    float4 regs[4] = {float4(0.0), params.regs[0],\n"
             "                      params.regs[1], params.regs[2]};\n"
             "    for (uint index = 0u; index < params.stage_count; ++index) {\n"
             "        uint4 stage = params.stage_words[index];\n"
             "        uint coord = cc_tev_byte(stage, 0u);\n"
             "        uint raster = cc_tev_byte(stage, 1u);\n"
             "        uint slot = cc_tev_byte(stage, 2u) |\n"
             "                    ((cc_tev_byte(stage, 3u) & 1u) << 8u);\n"
             "        uint flags = cc_tev_byte(stage, 3u);\n"
             "        float4 tex = float4(1.0);\n"
             "        if (coord < 4u) {\n"
             "            float2 uv = coord == 0u ? input.uv0 :\n"
             "                        coord == 1u ? input.uv1 :\n"
             "                        coord == 2u ? input.uv2 : input.uv3;\n"
             "            switch (slot) {\n"
             "                case 0u:\n"
             "                    tex = image0.sample(sampler0, uv);\n"
             "                    break;\n"
             "                case 1u:\n"
             "                    tex = image1.sample(sampler1, uv);\n"
             "                    break;\n"
             "                case 2u:\n"
             "                    tex = image2.sample(sampler2, uv);\n"
             "                    break;\n"
             "                case 3u:\n"
             "                    tex = image3.sample(sampler3, uv);\n"
             "                    break;\n"
             "                default:\n"
             "                    break;\n"
             "            }\n"
             "        }\n"
             "        tex = cc_tev_swizzle(tex,\n"
             "            params.swap[(flags >> 3u) & 3u]);\n"
             "        float4 ras = (raster == 255u || raster == 6u ||\n"
             "                      raster == 7u) ? float4(0.0) : input.color;\n"
             "        ras = cc_tev_swizzle(ras,\n"
             "            params.swap[(flags >> 1u) & 3u]);\n"
             "        uint color_ab = cc_tev_byte(stage, 4u);\n"
             "        uint color_cd = cc_tev_byte(stage, 5u);\n"
             "        uint color_op = cc_tev_byte(stage, 6u);\n"
             "        uint color_control = cc_tev_byte(stage, 7u);\n"
             "        uint alpha_ab = cc_tev_byte(stage, 8u);\n"
             "        uint alpha_cd = cc_tev_byte(stage, 9u);\n"
             "        uint alpha_op = cc_tev_byte(stage, 10u);\n"
             "        uint alpha_control = cc_tev_byte(stage, 11u);\n"
             "        float3 kcolor = cc_tev_kcolor(color_control >> 3u, params);\n"
             "        float kalpha = cc_tev_kalpha(alpha_control >> 3u, params);\n"
             "        float3 color = cc_tev_color_op(color_ab, color_cd,\n"
             "            color_op, color_control, regs, tex, ras, kcolor);\n"
             "        float alpha = cc_tev_alpha_op(alpha_ab, alpha_cd,\n"
             "            alpha_op, alpha_control, regs, tex, ras, kalpha);\n"
             "        uint color_dest = (color_control >> 1u) & 3u;\n"
             "        uint alpha_dest = (alpha_control >> 1u) & 3u;\n"
             "        float4 target = regs[color_dest];\n"
             "        target.rgb = color;\n"
             "        regs[color_dest] = target;\n"
             "        target = regs[alpha_dest];\n"
             "        target.a = alpha;\n"
             "        regs[alpha_dest] = target;\n"
             "    }\n"
             "    float4 p = regs[0];\n"
             "    uint comparisons = params.alpha_comparisons;\n"
             "    uint operation = params.alpha_operation;\n"
             "    if (comparisons != 0x77u || operation >= 2u) {\n"
             "        float alpha = cc_tev_alpha8(p.a);\n"
             "        if (!cc_alpha_passes(comparisons, operation,\n"
             "                             params.alpha_references, alpha)) {\n"
             "            discard_fragment();\n"
             "        }\n"
             "    }\n"
             "    return p;\n"
             "}\n"];
}
